"""empty message

Revision ID: 9fe494e3908a
Revises: 81c185e056b7
Create Date: 2016-08-27 06:44:12.659966

"""

# revision identifiers, used by Alembic.
revision = '9fe494e3908a'
down_revision = '81c185e056b7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
